name: Test C++ Unit Tests
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openroad/ubuntu-cpp20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.8
      - name: Install C++20-compatible LEMON
        run: |
          git clone --depth=1 -b 1.3.1 \
            https://github.com/The-OpenROAD-Project/lemon-graph.git /tmp/lemon-graph
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -B /tmp/lemon-graph/build /tmp/lemon-graph
          cmake --build /tmp/lemon-graph/build -j"$(nproc)" --target install
      - name: Build OpenROAD
        run: |
          cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -GNinja -B build .
          cd build
          CLICOLOR_FORCE=1 ninja build_and_test

